# Welcome to Jom Jose Blog!

# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings

title: "Jom Jose Blog"
email: jomjose.engr@gmail.com
description: Articles on JavaScript, HTML5, CSS3, front-end architecture and web performance.
baseurl: "" # the subpath of my site
url: "https://jomjose.github.io" # the base hostname & protocol for my site
twitter_username: jomjoseblog
github_username:  jomjose

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - jomjoseblog.config.js
  - gulpfile.js
  - LICENSE
  - node_modules
  - npm-debug.log
  - package.json
  - README.md

permalink: /:title/

# Default variables
defaults:
  -
    scope:
      path: ""
    values:
      layout: "article"
      tags: []
      author: Jom Jose